services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: ww_admin
    ports:
      - "5432:5432"
    volumes:
      - ww_pgdata:/var/lib/postgresql/data
volumes:
  ww_pgdata: