# Generated by Django 5.1.6 on 2025-03-04 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SC_ADMIN', 'School Admin'), ('POLICE', 'Police')], max_length=50)),
                ('jursidction', models.ManyToManyField(blank=True, related_name='officers', to='accounts.school')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='accounts.school')),
            ],
        ),
    ]
