# Generated by Django 5.1.6 on 2025-03-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='nces_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
