# Generated by Django 5.1.6 on 2025-09-02 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='cam_id',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='recording',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='recording start time'),
        ),
    ]
