# Generated by Django 5.1.6 on 2025-09-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_recording_cam_id_recording_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='camera_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
